import type { Metadata } from "next";
import "./globals.css";
import { Confetti } from "./confetti";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Confetti>{children}</Confetti>
      </body>
    </html>
  );
}
